### ISSUE TITLE
Help make this project unnecessary

### ISSUE THREAD

**Issue by jeff5** [scijava/jython-shaded#7]
Thanks for providing this way of using Jython in spite of the dependency situation. In the latest version of Jython (now in beta) we offer a JAR that contains only our unique code: dependencies are listed in the associated POM. (https://search.maven.org/artifact/org.python/jython-slim/2.7.2b2/jar)

Have we done this well enough that the "naive way to add a Jython dependency" (to quote your README.md) just works for you and your constituency? Works, that is, if you call it `jython-slim`.

If not, I'd like to get this right before 2.7.2 is final.

**Comment by ctrueden** [comment]
Thanks @jeff5 for working on this, and for the issue here!

I have now done the following things:

1. Updated https://github.com/scijava/scripting-jython to include a test of `os.getpid()` (see #5 for why).
2. Updated scripting-jython to depend on `org.python:jython-slim:2.7.2b2` instead of `org.scijava:jython-shaded:2.7.1.1`, and verified that all tests still pass.
3. Using jgo, spun up a combined SciJava REPL including the new scripting-jython, scripting-jruby, and other JSR-223 script languages, and checked that both Jython and JRuby scripts still execute successfully, and that Java's classpath looks consistent.
4. Released a new [version 0.5.0 of scripting-jython to the SciJava Maven repository](https://maven.scijava.org/#nexus-search;gav~org.scijava~scripting-jython~0.5.0~~) that depends on jython-slim.
5. Installed the new scripting-jython into a test [Fiji](https://fiji.sc/) environment locally, and verified that real-world Jython scripting examples still work.
6. Invited the motivated ImageJ developer community to test further [via Gitter](https://gitter.im/imagej/imagej?at=5dc03edd9825bd6bac2639cd).

So to answer your question:

> Have we done this well enough that the "naive way to add a Jython dependency" (to quote your README.md) just works for you and your constituency?

Yes! Great work! Thank you! :tada:

I'll ship this to our users soon, and ask them to do some further testing, and report any issues back (is [this](https://bugs.jython.org/) the best issue tracker to use?).

**Comment by ctrueden** [comment]
Heads up to @mslinn @mikus @larsrh @headius @shenberg: check out `org.python:jython-slim:2.7.2b2`, and please report back to @jeff5 et al. any issues you encounter. Thanks!

**Comment by jeff5** [comment]
Yes https://bugs.jython.org is the place for now, although we also pay attention to https://github.com/jythontools/jython/issues .

I'm least sure about the way I have named specific version in the dependencies. It is difficult, however, to make a looser claim (and stand by it) without more testing than we can do.

**Comment by ctrueden** [comment]
I am almost done updating our ecosystem to use jython-slim instead of jython-shaded. But I came across one issue with combining Jython and JRuby on the same classpath: jruby/jruby#6205. I don't think it's a problem with Jython—I'm just cross-linking it here in the interest of transparency.

**Comment by jeff5** [comment]
In writing:

> I'm least sure about the way I have named specific version in the dependencies. ...

this is the sort of thing I meant, although I only foresaw clashes of preferred version.
